### ISSUE TITLE
Jail MAC address

### ISSUE THREAD

**Issue by tschettervictor** [cbsd/xigmajail#5]
I am hoping to use CBSD extension for my new XigmaNAS installation. I have a question though.

Does CBSD retain the MAC address of the jail when it is restarted?

in iocage, the MAC address is given based on the name, so it stays the same when a jail reboots. 

In bastillebsd though, the MAC changes on every jail reboot. This is bad as we do MAC filtering.

**Comment by olevole** [comment]
Hi, the improvements of the cbsd plugin for XigmaNAS are still in todo ;)

As for the HWADDR/MAC address - yes, cbsd generates a unique MAC address and saves it in the database, so the MAC address is unchanged.

default MAC_PREFIX or OUI ([Organizationally unique identifier](https://en.wikipedia.org/wiki/Organizationally_unique_identifier) is '00:a0:98' ):

![image](https://github.com/user-attachments/assets/9d64122a-3f74-4c91-bbd3-0f25348b61a1)

can be changed via `jset` or `cbsd jconfig` -> `jailnic` ...

**Comment by tschettervictor** [comment]
Thanks. Could you point me to the relevant code that generates the MAC. I'm trying to do something similar with Bastille.

**Comment by olevole** [comment]
https://github.com/cbsd/cbsd/blob/v14.1.2/subr/tools.subr#L504-L523
